### ISSUE TITLE
Error: Could not open library

### ISSUE THREAD

**Issue by ghost** [toppair/peek.nvim#18] opened 2023-01-16 04:50 UTC
**Describe the bug**

Newly installed via `lazy.nvim`, use the default settings.

Called the function `lua require('peek').open()` via the command line, in a markdown buffer.

Error popped.

**To Reproduce**

see above

**Expected behavior**

**Screenshots**
![2023-01-16_12-26](https://user-images.githubusercontent.com/8101584/212600466-4908e02e-3b7d-4a52-9c53-f9d6bb8eaa10.png)
**Desktop (please complete the following information):**
 -   OS: Arch Linux ARM aarch64
 -  Host: Apple MacBook Pro (14-inch, M1 Max, 2021)
 -  Kernel: 6.1.0-asahi-2-2-edge-ARCH
 - `nvim --version`:
```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```
 - `deno --version`:
```
deno 1.28.3 (release, aarch64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.8.3
```
 - plugin setup:
```lua
{
    "toppair/peek.nvim",
    name = "peek",
    build = "deno task--quiet build:fast",
    ft = {"markdown"},
    config = function()
        require("peek").setup()
    end,
 },
```
**Additional context**

The plugin is ensured to be loaded before `open` function

**Comment by MichaelC001** [comment] 2023-02-02 03:44
peek open error:

public/main.bundle.js   not found

mac os

thank you

**Comment by dragove** [comment] 2023-02-18 08:53
install `webkit2gtk`  package in `Arch Linux` solved this problem.

**Comment by toppair** [comment] 2024-03-14 17:05
Duplicate of #51

**Closed by toppair** 2024-03-14 17:05 UTC
Labels: bug
